# Generated by Django 4.1.4 on 2022-12-07 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=50)),
                ('image', models.TextField(max_length=256)),
                ('info', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('date_text', models.CharField(max_length=20)),
                ('time_text', models.CharField(max_length=10)),
                ('country1', models.CharField(max_length=50)),
                ('country2', models.CharField(max_length=50)),
                ('country1code', models.CharField(max_length=50)),
                ('country2code', models.CharField(max_length=50)),
                ('country1goals', models.PositiveIntegerField()),
                ('country2goals', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=256)),
                ('image', models.TextField(max_length=256)),
                ('text', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField()),
                ('image', models.TextField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predictions_cnt', models.PositiveIntegerField(default=0)),
                ('score', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.PositiveIntegerField()),
                ('country1goals', models.PositiveIntegerField()),
                ('country2goals', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
