# Generated by Django 4.1.4 on 2022-12-08 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
    ]
