# Generated by Django 4.1.4 on 2022-12-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_profile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='admin', max_length=50),
            preserve_default=False,
        ),
    ]
